ietf-wg-webtrans/draft-ietf-webtrans-http2

draft-kinnear-webtransport-http2.md
Add brief section describing Http2Transport's stance on the properties enumerated in the WebTransport Overview. 
We can move this around later as necessary, but wanted to get the text in to document which optional properties are supported and which are not.
Closes #8.
=> #8 Enumerate the transport properties provided by Http2Transport

draft-ietf-webtrans-http2.md
This might seem unfortunate, but it's how the protocol works.
Update the link to point to HTTP spec instead.
=> The query component is relevant too

draft-ietf-webtrans-http2.md
Two things:
1. Say what the header contains
2. Limit it to the Web
And fix the xref formatting.
=> Origin header tweak

draft-ietf-webtrans-http2.md
The features and protocol details are really different concepts (one
relates to what the protocol does, the other to the implications of
that), but the current structure is poor.  I was taught that you never
leave a section heading empty (S5 currently) and that you never have
just a single subsection (S4.1 and S5.1).  Expanding the scope of the
section is an elegant solution.
=> Fewer headings

draft-ietf-webtrans-http2.md
The frame format depends on having a definition.  I've also made a
requirement for this to be zero values.  Do we need to say that
recipients MUST NOT validate this or that they MAY opt to avoid
validation.
=> Padding field in WT_PADDING

draft-ietf-webtrans-http2.md
There is not "right" place to put these, but as they are fairly large
(and not that useful, frankly), I am going to suggest that they go after
the frame definitions.
=> Move the Examples out of IANA considerations

draft-ietf-webtrans-http2.md
Make the definition of fields use definition lists.
Use superscripts where appropriate.  Also, fix this so that it is
2^62-1 and not 2^61 (parentheses were used incorrectly).
=>  Some clerical changes 

draft-ietf-webtrans-http2.md
There is a long and proud legacy of drafts that carry introductions concentrating on the
motivations for the last design change rather than the true reasons for
the protocol.  This is my attempt to bring things back on the level.
I didn't stop there though.  I think that we should make this about
HTTP/2 because we don't currently have an extended CONNECT defined for
HTTP/1.1.  This walks back some of the "generic HTTP" language.  More
changes might be needed later in the document for that to be complete,
but I wanted to keep this fix localized.
I did cut stuff that I think the document should still contain.  I just don't think that these need to be in the introduction.
That is:
* you can multiplex multiple sessions
* other protocols might take stuff from this session and transmit them in …
=> A new shorter intro

draft-ietf-webtrans-http2.md
I make a few word-level adjustments, but the goal here was to tweak the
way that this defines key concepts.
I added one concept "WebTransport frames", which isn't necessarily a
global concept, but it might be useful in this document to distinguish
between HTTP/2 frames and the stuff in Section 6.
I also linked up the frame types.  I've a change that I'm going to propose to kramdown that should make this a whole lot less unpleasant to use for the general case.
=> Improvements to overview 

draft-ietf-webtrans-http2.md
The definition was a little loose, so I rewrote it.
We only need to use 0x0a and 0x0b, which is lucky and it lets us avoid
much of the mess that QUIC has around bits in the type.
I've also added definitions for the fields in the frame.
=> Fix the definition of WT_STREAM

draft-ietf-webtrans-http2.md
Reset stream doesn't cease retransmission. Closes #53
=> Reset stream doesn't cease retransmission. Closes #53

draft-ietf-webtrans-http2.md
Capsule design team output. Tries to avoid touching flow control so that we can tackle the open issues there separately, but converts the rest of HTTP/2 over to using capsules, as discussed. See also [HTTP/3](https://github.com/ietf-wg-webtrans/draft-ietf-webtrans-http3/pull/86).
Same content as [draft PR](https://github.com/ekinnear/draft-ietf-webtrans-http2/pull/1), thank you to those who have already reviewed!
Closes #25
Closes #51
=> Capsule design team output [HTTP/2]

draft-ietf-webtrans-http2.md
Bring over text from HTTP/3 about refused stream
This aligns the two documents. We can probably further tweak this wording, but if we do, we should update it everywhere.
Closes #83
=> Bring over text from HTTP/3 about refused stream

draft-ietf-webtrans-http2.md
Clarify END_STREAM and be less specific about individual framing boundaries
Closes #106
=> Clarify END_STREAM and be less specific about individual framing boundaries

draft-ietf-webtrans-http2.md
As noted in #109, we need to signal to the receiver when a sender opts to use a reliable reset.  Rather than add a second frame type, we can just build a single reset that has the additional feature.  As @vasilvv pointed out, if we were going to do QUIC over again, we'd build this into RESET_STREAM.
This is not a backward-compatible change, so we'll need to change version numbers (I have not done that here).
Closes #109.
=> Add a reliable size to WT_RESET_STREAM

draft-ietf-webtrans-http2.md
Use the same subprotocol negotiation mechanism as HTTP/3
Fixes #108
=> Use the same subprotocol negotiation mechanism as HTTP/3

draft-ietf-webtrans-http2.md
Update and rename subprotocol negotiation to match HTTP/3.
Also fix reference.
Closes #114.
=> Update and rename subprotocol negotiation to match HTTP/3

draft-ietf-webtrans-http2.md
Rename DRAIN_WEBTRANSPORT_SESSION to WT_DRAIN_SESSION and CLOSE_WEBTRANSPORT_SESSION to WT_CLOSE_SESSION
Fixes #119
=> Rename DRAIN_WEBTRANSPORT_SESSION to WT_DRAIN_SESSION and CLOSE_WEBTRANSPORT_SESSION to WT_CLOSE_SESSION

draft-ietf-webtrans-http2.md
Rename WebTransport -> WT for SETTINGS
Based on top of https://github.com/ietf-wg-webtrans/draft-ietf-webtrans-http2/pull/128, will rebase once that lands.
This is purely a find-and-replace + whitespace changes, the text itself should otherwise be identical.
Fixes #127
=> Rename WebTransport -> WT for SETTINGS

draft-ietf-webtrans-http2.md
After reading the document, I was left wondering how the directionality of a new streams is communicated. I believe that this is done by selecting a stream ID with the corresponding second least significant bit. If that's the case, I think the description for the WT_STREAM capsule could be expanded.
=> Explain selecting stream directionality
