draft-kinnear-webtransport-http2.md
=> Add unidirectional flag to WTHEADERS

.note.xml, draft-ietf-webtrans-http2.md
Add links to the links.
Remove .note.xml, which wasn't being used.
=> Fix the note

draft-ietf-webtrans-http2.md
QUIC is complicated, this doesn't need to be.
=> Simplify the definition of MAX_DATA

draft-ietf-webtrans-http2.md
The resource does.  It's a fine distinction, but an important one.
=> The server doesn't support WT

draft-ietf-webtrans-http2.md
And explain the difference.
Closes #29.
=> Cut Final Size

draft-ietf-webtrans-http2.md
...Not HTTP/2
This section might go, but this is also harmless.
=> Use MPTCP RFC

draft-ietf-webtrans-http2.md
Attempting to be minimal and just point at RFC9000. 
Fixes #28.
=> Add text describing Stream ID numbering

README.md, draft-ietf-webtrans-http2.md
=> Replace "using HTTP/2" with "over HTTP/2"

draft-ietf-webtrans-http2.md
Change 404 to 406 Not Acceptable
Closes #61
=> Update status code

draft-ietf-webtrans-http2.md
=> Stop forbidding capsules before session is accepted

draft-ietf-webtrans-http2.md
=> Add note about padding in HTTP/2

draft-ietf-webtrans-http2.md
Moved the later section up, fixed up some sections, and consolidated some of the text.
Closes #48
=> Merge transport considerations and transport properties

draft-ietf-webtrans-http2.md
=> Switch from 200 to 2xx

draft-ietf-webtrans-http2.md
=> Add initial flow control windows

draft-ietf-webtrans-http2.md
Expand description of flow control and add additional notes
@martinthomson already wrote up a very nice overview of the layers we have, so added a little bit extra there and filled in the last little bit on limiting streams within a session to round everything out.
Closes #27
=> Expand description of flow control and add additional notes

draft-ietf-webtrans-http2.md
Remove SETTINGS_ENABLE_WEBTRANSPORT in favor of SETTINGS_WEBTRANSPORT_MAX_SESSIONS.
Closes #73
=> Remove SETTINGS_ENABLE_WEBTRANSPORT

draft-ietf-webtrans-http2.md
Add settings for initial limits, with defaults of "0".
Fixes #72
Fixes #71
=> Add settings for initial limits

draft-ietf-webtrans-http2.md
No idea why I stalled on this one for so long.  I wonder if we want to add more examples (eg: uni directional streams, datagrams, flow control, etc).
Fixes: #32
=> Update examples with correct stream IDs

draft-ietf-webtrans-http2.md
Helps, but does not fully resolve #83
=> Change 426->429

draft-ietf-webtrans-http2.md
Renumber settings to fit in 16 bits
Closes #89
=> Renumber settings to fit in 16 bits

draft-ietf-webtrans-http2.md
Clarify flow control interactions
Closes #88
=> Clarify flow control interactions

draft-ietf-webtrans-http2.md
Add close and drain WebTransport session capsules
Fixes #95
=> Add close and drain WebTransport session capsules

draft-ietf-webtrans-http2.md
I found myself with some time, so I thought that I'd do a bad job and see what happened.
=> Error handling

draft-ietf-webtrans-http2.md
Update settings based on latest H3 changes, including examples.
Also include considerations for future versions.
Fixes #105
=> Update settings based on latest H3 changes, including examples. 

draft-ietf-webtrans-http2.md
Be more strict about flow control violations for H2
Fixes #94
=> Be more strict about flow control violations for H2

draft-ietf-webtrans-http2.md
=> Add Key Exporters and associated TLS requirements

draft-ietf-webtrans-http2.md
Update text around PADDING minimum size
Fixes #134
=> Update text around PADDING minimum size

draft-ietf-webtrans-http2.md
Add handling for unknown keys in the WebTransport-Init dictionary
Fixes #136
=> Add handling for unknown keys in the WebTransport-Init dictionary
